- name: Setup db
  hosts: db
  remote_user: nkosl
  become: true
  vars:
    ansible_ssh_pipelining: true

  tasks:
    - name: Install postgresql
      apt:
        name: [git, postgresql=13+225, libpq-dev, python3-psycopg2]
        state: present
    - name: Setup postgresql user
      become_user: postgres
      postgresql_user:
        name: nkosl
        password: nkosl
        role_attr_flags: SUPERUSER
    - name: Create postgres db
      become: false
      postgresql_db:
        login_user: nkosl
        login_password: nkosl
        name: nkosl
        state: present
    - name: Pull repo
      git:
        repo: https://github.com/KSET/nkosl-www.git
        version: master
        dest: /opt/nkosl-www
    - name: Populate postgres db
      become: false
      block:
        - name: Create posts
          postgresql_query:
            login_user: nkosl
            login_password: nkosl
            db: nkosl
            path_to_script: /opt/nkosl-www/db/scripts/create_posts.sql
        - name: Fill posts
          postgresql_query:
            login_user: nkosl
            login_password: nkosl
            db: nkosl
            path_to_script: /opt/nkosl-www/db/scripts/fill_posts.sql
      rescue:
        - name: Ignore error
          command: echo
    - name: Update postgres listen addresses
      lineinfile:
        path: /etc/postgresql/13/main/postgresql.conf
        regexp: '# listen_addresses'
        line: "listen_addresses = '*'"
    - name: Update postgres hba
      lineinfile:
        path: /etc/postgresql/13/main/pg_hba.conf
        line: 'host nkosl nkosl 10.0.2.2/32 trust'
    - name: Restart postgres
      service:
        enabled: true
        name: postgresql
        state: restarted
