- name: Setup app with mock data
  hosts: app
  remote_user: nkosl
  become: yes

  tasks:
    - name: Install git nginx pip
      apt:
        name: [git, nginx, python3-pip, libpq-dev]
        state: present
    - name: Pull mock repo
      git:
        repo: https://github.com/KSET/nkosl-www.git
        version: mock
        dest: /opt/nkosl-www
    - name: Install virtualenv
      pip:
        name: virtualenv
    - name: Install python requirements
      pip: 
        requirements: /opt/nkosl-www/app/nkosl-blog/requirements.txt
        virtualenv: /home/nkosl/nkosl_env
        virtualenv_python: python3
    - name: Add nkosl systemd service
      copy:
        remote_src: true
        src: /opt/nkosl-www/nkosl_blog.service
        dest: /etc/systemd/system/nkosl_blog.service
    - name: Start nkosl systemd service
      systemd:
        name: nkosl_blog
        state: started
    - name: Delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
    - name: Add nkosl nginx server
      copy:
        remote_src: true
        src: /opt/nkosl-www/nkosl_blog.conf
        dest: /etc/nginx/sites-enabled/nkosl_blog.conf
    - name: Reload nginx
      service:
        name: nginx
        state: restarted
